# Generated by Django 5.2.1 on 2025-09-24 19:20

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(default=posts.models.default_expiry),
        ),
    ]
