# Generated by Django 5.2.1 on 2025-10-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auto_approve_at',
        ),
        migrations.DeleteModel(
            name='ApprovalQueue',
        ),
    ]
