# Generated by Django 5.2.1 on 2025-10-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0002_country_phone_code'),
        ('posts', '0002_post_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglocationrequest',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_pending_requests', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_continent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_specific_continent', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_country',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_specific_country', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_state',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_specific_state', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_town',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_specific_town', to='custom_search.town'),
        ),
    ]
