# Generated by Django 5.1.5 on 2025-02-17 02:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_post_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
