# Generated by Django 5.1.5 on 2025-02-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_author_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagei',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
