# Generated by Django 5.2.1 on 2025-05-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0002_pendinglocationrequest'),
        ('posts', '0003_post_availability_schedule_post_brand_post_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_continent', to='custom_search.continent'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_continent_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_country', to='custom_search.country'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_country_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_state', to='custom_search.state'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_state_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_town', to='custom_search.town'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_town_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
