# Generated by Django 5.2.1 on 2025-05-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post_continent_post_post_continent_input_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_icons/')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.RemoveField(
            model_name='post',
            name='town',
        ),
        migrations.RemoveField(
            model_name='post',
            name='use_default_location',
        ),
        migrations.RemoveField(
            model_name='socialmediahandle',
            name='handle',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='product_name',
            field=models.CharField(default='ExamplePostBut_laterBypassed', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmediahandle',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_handles', to='posts.post'),
        ),
    ]
