# Generated by Django 5.1.5 on 2025-02-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_imagei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagei',
            new_name='imageii',
        ),
    ]
