# Generated by Django 5.1.5 on 2025-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_imagei_post_imageii'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageiii',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
