# Generated by Django 5.1.5 on 2025-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_imageiii'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageiv',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
