# Generated by Django 5.2.1 on 2025-05-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_availability_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='service_details',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=50, null=True),
        ),
    ]
