# Generated by Django 5.2.1 on 2025-06-09 10:07

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_service_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='labor_area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='labor_references',
        ),
        migrations.RemoveField(
            model_name='post',
            name='labor_skills',
        ),
        migrations.RemoveField(
            model_name='post',
            name='labor_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='service_duration',
        ),
        migrations.RemoveField(
            model_name='post',
            name='service_region',
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('fairly used', 'Fairly Used')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=posts.models.post_image_upload_path),
        ),
    ]
