# Generated by Django 5.2.1 on 2025-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_availability_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='availability_scope',
            field=models.CharField(choices=[('global', 'Global'), ('continent', 'Continent-wide'), ('country', 'Country-wide'), ('state', 'State-wide'), ('town', 'Town-specific')], default='town', help_text='Defines the scope of availability for this post (e.g., specific town, entire state, etc.).', max_length=10),
        ),
    ]
