# Generated by Django 5.2.1 on 2025-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_availability_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
