# Generated by Django 5.1.6 on 2025-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_image_remove_post_imageii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
