# Generated by Django 5.2.1 on 2025-07-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_continent_input',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_country_input',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_state_input',
        ),
    ]
