# Generated by Django 5.2.1 on 2025-08-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0006_alter_continent_id_alter_country_id_and_more'),
        ('posts', '0011_post_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_continent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_continent', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_country',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_country', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_state',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_state', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_town',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_specific_town', to='custom_search.town'),
        ),
    ]
