# Generated by Django 5.2.1 on 2025-08-22 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_post_continent_alter_post_post_country_and_more'),
        ('posts', '0013_auto_create_categories'),
    ]

    operations = [
    ]
