# Generated by Django 5.2.1 on 2025-08-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0008_delete_pendinglocationrequest'),
        ('posts', '0015_pendinglocationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinglocationrequest',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_requests', to='custom_search.state'),
        ),
        migrations.AddField(
            model_name='pendinglocationrequest',
            name='typed_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
