# Generated by Django 5.2.1 on 2025-09-05 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0008_delete_pendinglocationrequest'),
        ('posts', '0016_pendinglocationrequest_parent_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglocationrequest',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pending_requests', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='pendinglocationrequest',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_location_requests', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
