# Generated by Django 5.2.1 on 2025-10-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='town',
            name='code',
            field=models.CharField(db_index=True, default='TEMP', max_length=5),
        ),
    ]
