# Generated by Django 5.2.1 on 2025-05-19 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_continent', models.CharField(blank=True, max_length=100, null=True)),
                ('typed_country', models.CharField(blank=True, max_length=100, null=True)),
                ('typed_state', models.CharField(blank=True, max_length=100, null=True)),
                ('typed_town', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
