# Generated by Django 5.1.6 on 2025-04-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='town',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='custom_search.state'),
        ),
    ]
