# Generated by Django 5.2.1 on 2025-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
