# Generated by Django 5.1.6 on 2025-04-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0002_alter_continent_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
