# Generated by Django 5.2.1 on 2025-08-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0005_auto_20250725_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendinglocationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='town',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
