# Generated by Django 5.2.1 on 2025-08-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0006_alter_continent_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinglocationrequest',
            name='typed_continent',
        ),
        migrations.RemoveField(
            model_name='pendinglocationrequest',
            name='typed_country',
        ),
        migrations.RemoveField(
            model_name='pendinglocationrequest',
            name='typed_state',
        ),
    ]
