# Generated by Django 5.2.1 on 2025-08-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0007_remove_pendinglocationrequest_typed_continent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingLocationRequest',
        ),
    ]
