# Generated by Django 5.2.1 on 2025-06-26 19:12

import django.db.models.deletion
import phonenumber_field.modelfields
import seekers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_search', '0002_pendinglocationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeekerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('labor', 'Labor')], max_length=20)),
                ('availability_scope', models.CharField(choices=[('global', 'Global'), ('continent', 'Continent-wide'), ('country', 'Country-wide'), ('state', 'State-wide'), ('town', 'Town-specific')], default='town', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('post_continent_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_country_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_state_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_town_input', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_fulfillment_time', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seekers_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts', to='seekers.seekercategory')),
                ('post_continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers_post_continent', to='custom_search.continent')),
                ('post_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers_post_country', to='custom_search.country')),
                ('post_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers_post_state', to='custom_search.state')),
                ('post_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seekers_post_town', to='custom_search.town')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeekerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=seekers.models.seeker_image_upload_path)),
                ('seeker_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seekers.seekerpost')),
            ],
        ),
    ]
