# Generated by Django 5.2.1 on 2025-10-18 10:21

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import seekers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, unique=True)),
            ],
            options={
                'verbose_name': 'Seeker Category',
                'verbose_name_plural': 'Seeker Categories',
                'db_table': 'seeker_category',
            },
        ),
        migrations.CreateModel(
            name='SeekerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_scope', models.CharField(choices=[('global', 'Global'), ('continent', 'Continent-wide'), ('country', 'Country-wide'), ('state', 'State-wide'), ('town', 'Town-specific')], default='town', help_text='Defines the scope of availability for this post (e.g., specific town, entire state, etc.).', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('post_continent_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_country_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_state_input', models.CharField(blank=True, max_length=100, null=True)),
                ('post_town_input', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_fulfillment_time', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=seekers.models.default_expiry)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, help_text="Category for this seeker post. Defaults to 'General'.", on_delete=django.db.models.deletion.CASCADE, to='seekers.seekercategory')),
                ('post_continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_continent', to='custom_search.continent')),
                ('post_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_country', to='custom_search.country')),
                ('post_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_state', to='custom_search.state')),
                ('post_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_town', to='custom_search.town')),
            ],
            options={
                'verbose_name': 'Seeker Post',
                'verbose_name_plural': 'Seeker Posts',
                'db_table': 'seeker_post',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PendingSeekerLocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_town', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('parent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_pending_requests', to='custom_search.state')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_location_request', to='seekers.seekerpost')),
            ],
            options={
                'verbose_name': 'Pending Seeker Location Request',
                'verbose_name_plural': 'Pending Seeker Location Requests',
                'db_table': 'pending_seeker_location_request',
            },
        ),
        migrations.CreateModel(
            name='SeekerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_received_responses', to=settings.AUTH_USER_MODEL)),
                ('seeker_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_responses', to='seekers.seekerpost')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_sent_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seeker Response',
                'verbose_name_plural': 'Seeker Responses',
                'db_table': 'seeker_response',
            },
        ),
        migrations.CreateModel(
            name='SeekerSocialMediaHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_social_handles', to='seekers.seekerpost')),
            ],
            options={
                'verbose_name': 'Seeker Social Media Handle',
                'verbose_name_plural': 'Seeker Social Media Handles',
                'db_table': 'seeker_social_media_handle',
            },
        ),
    ]
