# Generated by Django 5.2.1 on 2025-09-24 19:20

import seekers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerpost',
            name='expires_at',
            field=models.DateTimeField(default=seekers.models.default_expiry),
        ),
    ]
