# Generated by Django 5.2.1 on 2025-10-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0002_country_phone_code'),
        ('seekers', '0002_seekerpost_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingseekerlocationrequest',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_pending_requests', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_continent', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_country', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_state', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts_town', to='custom_search.town'),
        ),
    ]
