# Generated by Django 5.2.1 on 2025-07-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0002_seekerpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
