# Generated by Django 5.2.1 on 2025-07-14 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0004_remove_seekerpost_category_delete_seekercategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_responses', to=settings.AUTH_USER_MODEL)),
                ('seeker_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='seekers.seekerpost')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
