# Generated by Django 5.2.1 on 2025-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0005_seekerresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerpost',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
