# Generated by Django 5.2.1 on 2025-09-05 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0008_delete_pendinglocationrequest'),
        ('seekers', '0006_seekerpost_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=77, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='seekerpost',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='seekerimage',
            old_name='seeker_post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='seekerpost',
            name='request_type',
        ),
        migrations.AddField(
            model_name='seekerpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='availability_scope',
            field=models.CharField(choices=[('global', 'Global'), ('continent', 'Continent-wide'), ('country', 'Country-wide'), ('state', 'State-wide'), ('town', 'Town-specific')], default='town', help_text='Defines the scope of availability for this post (e.g., specific town, entire state, etc.).', max_length=10),
        ),
        migrations.AddField(
            model_name='seekerpost',
            name='category',
            field=models.ForeignKey(default=1, help_text="Category for this seeker post. Defaults to 'General'.", on_delete=django.db.models.deletion.CASCADE, to='seekers.category'),
        ),
        migrations.CreateModel(
            name='PendingLocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_town', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('parent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_pending_requests', to='custom_search.state')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_location_request', to='seekers.seekerpost')),
            ],
        ),
    ]
