# Generated by Django 5.2.1 on 2025-09-11 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0008_delete_pendinglocationrequest'),
        ('seekers', '0008_seekersocialmediahandle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PendingLocationRequest',
            new_name='PendingSeekerLocationRequest',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='SeekerCategory',
        ),
        migrations.AlterModelOptions(
            name='pendingseekerlocationrequest',
            options={'verbose_name': 'Pending Seeker Location Request', 'verbose_name_plural': 'Pending Seeker Location Requests'},
        ),
        migrations.AlterModelOptions(
            name='seekercategory',
            options={'verbose_name': 'Seeker Category', 'verbose_name_plural': 'Seeker Categories'},
        ),
        migrations.AlterModelOptions(
            name='seekerimage',
            options={'verbose_name': 'Seeker Image', 'verbose_name_plural': 'Seeker Images'},
        ),
        migrations.AlterModelOptions(
            name='seekerpost',
            options={'ordering': ['-date'], 'verbose_name': 'Seeker Post', 'verbose_name_plural': 'Seeker Posts'},
        ),
        migrations.AlterModelOptions(
            name='seekerresponse',
            options={'verbose_name': 'Seeker Response', 'verbose_name_plural': 'Seeker Responses'},
        ),
        migrations.AlterModelOptions(
            name='seekersocialmediahandle',
            options={'verbose_name': 'Seeker Social Media Handle', 'verbose_name_plural': 'Seeker Social Media Handles'},
        ),
        migrations.AlterField(
            model_name='seekerimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_images', to='seekers.seekerpost'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_posts_continent', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_posts_country', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_posts_state', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='seekerpost',
            name='post_town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeker_posts_town', to='custom_search.town'),
        ),
        migrations.AlterField(
            model_name='seekerresponse',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_received_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekerresponse',
            name='seeker_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_responses', to='seekers.seekerpost'),
        ),
        migrations.AlterField(
            model_name='seekerresponse',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_sent_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seekersocialmediahandle',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_social_handles', to='seekers.seekerpost'),
        ),
        migrations.AlterModelTable(
            name='pendingseekerlocationrequest',
            table='pending_seeker_location_request',
        ),
        migrations.AlterModelTable(
            name='seekercategory',
            table='seeker_category',
        ),
        migrations.AlterModelTable(
            name='seekerimage',
            table='seeker_image',
        ),
        migrations.AlterModelTable(
            name='seekerpost',
            table='seeker_post',
        ),
        migrations.AlterModelTable(
            name='seekerresponse',
            table='seeker_response',
        ),
        migrations.AlterModelTable(
            name='seekersocialmediahandle',
            table='seeker_social_media_handle',
        ),
    ]
