# Generated by Django 5.1.5 on 2025-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_home_town_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='visual_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
