# Generated by Django 5.2.1 on 2025-10-07 19:57

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_follow_options_customuser_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
