# Generated by Django 5.1.5 on 2025-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_age_customuser_visual_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='visual_id',
            new_name='virtual_id',
        ),
    ]
