# skipped_continent_mapping.py
# all countries listed here were not added to the main populate_state continent_mapping machine, and this is due to some real world issues like, some countries are not fully independent countries but are part of a larger nations (e.g "puerto Rico" is a part of the United States)
skipped_country_continent_mapping = {
    "Aruba": "North America",
    "Bonaire, Sint Eustatius and Saba": "North America",
    "Saint Barthélemy": "North America",
    "Bolivia, Plurinational State of": "South America",
    "Brunei Darussalam": "Asia",
    "Congo, The Democratic Republic of the": "Africa",
    "Curaçao": "North America",
    "Falkland Islands (Malvinas)": "South America",
    "Micronesia, Federated States of": "Oceania",
    "British Indian Ocean Territory": "Africa",
    "Iran, Islamic Republic of": "Asia",
    "Korea, Republic of": "Asia",
    "Lao People's Democratic Republic": "Asia",
    "Macao": "Asia",
    "Saint Martin (French part)": "North America",
    "Moldova, Republic of": "Europe",
    "Myanmar": "Asia",
    "Northern Mariana Islands": "Oceania",
    "Montserrat": "North America",
    "Martinique": "North America",
    "Mayotte": "Africa",
    "New Caledonia": "Oceania",
    "Norfolk Island": "Oceania",
    "Niue": "Oceania",
    "Pitcairn": "Oceania",
    "Puerto Rico": "North America",
    "Korea, Democratic People's Republic of": "Asia",
    "Palestine, State of": "Asia",
    "French Polynesia": "Oceania",
    "Réunion": "Africa",
    "Russian Federation": "Europe",
    "South Georgia and the South Sandwich Islands": "South America",
    "Saint Helena, Ascension and Tristan da Cunha": "Africa",
    "Svalbard and Jan Mayen": "Europe",
    "Saint Pierre and Miquelon": "North America",
    "Eswatini": "Africa",
    "Sint Maarten (Dutch part)": "North America",
    "Syrian Arab Republic": "Asia",
    "Turks and Caicos Islands": "North America",
    "Tokelau": "Oceania",
    "Türkiye": "Asia",
    "Taiwan, Province of China": "Asia",
    "Tanzania, United Republic of": "Africa",
    "United States Minor Outlying Islands": "Oceania",
    "United States": "North America",
    "Holy See (Vatican City State)": "Europe",
    "Venezuela, Bolivarian Republic of": "South America",
    "Virgin Islands, British": "North America",
    "Virgin Islands, U.S.": "North America",
    "Viet Nam": "Asia",
    "Wallis and Futuna": "Oceania"
}
