# Generated by Django 5.2.1 on 2025-09-17 10:42

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=person.models.profile_pic_upload_path, verbose_name='Profile Picture'),
        ),
    ]
