# Generated by Django 5.2.1 on 2025-12-27 20:05

import django.db.models.deletion
import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=person.models.gallery_upload_path, verbose_name='File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='Media Type')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
