# Generated by Django 5.1.5 on 2025-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_person_options_remove_person_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
