# Generated by Django 5.2.1 on 2025-10-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0002_country_phone_code'),
        ('person', '0002_alter_person_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglocationrequest',
            name='parent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_person_requests', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='person',
            name='continent',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_continent', to='custom_search.continent'),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_country', to='custom_search.country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_state', to='custom_search.state'),
        ),
        migrations.AlterField(
            model_name='person',
            name='town',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_town', to='custom_search.town'),
        ),
    ]
