# Generated by Django 5.1.5 on 2025-02-27 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_full_name',
        ),
        migrations.AddField(
            model_name='person',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Business Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='use_business_name',
            field=models.BooleanField(default=False, verbose_name='Use Business Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
