# Generated by Django 5.2.1 on 2025-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='real_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Real Name'),
        ),
    ]
