# Generated by Django 5.2.1 on 2025-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Users cannot edit their profile while pending approval.', max_length=10, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='person',
            name='review_message',
            field=models.TextField(blank=True, help_text='The admin selects a message to inform the user after verification.', null=True, verbose_name='Review Message'),
        ),
    ]
