# Generated by Django 5.1.5 on 2025-03-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0001_initial'),
        ('person', '0004_remove_person_person_full_name_person_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_search.continent'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_search.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_search.state'),
        ),
        migrations.AddField(
            model_name='person',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_search.town'),
        ),
    ]
