# Generated by Django 5.2.1 on 2025-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_approval_status_person_review_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='approval_status',
            field=models.CharField(choices=[('awaiting_user', 'awaiting_user'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_user', help_text='Users cannot edit their profile while pending approval.', max_length=15, verbose_name='Approval Status'),
        ),
    ]
