# Generated by Django 5.1.6 on 2025-03-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
