# Generated by Django 5.2.1 on 2025-08-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_search', '0008_delete_pendinglocationrequest'),
        ('person', '0007_alter_person_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='approval_status',
            field=models.CharField(choices=[('awaiting_user', 'Awaiting User'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='awaiting_user', help_text='Users cannot edit their profile while pending approval.', max_length=15, verbose_name='Approval Status'),
        ),
        migrations.CreateModel(
            name='PendingLocationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_town', models.CharField(blank=True, max_length=100, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('parent_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_person_requests', to='custom_search.state')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_location_request', to='person.person')),
            ],
        ),
    ]
