# Generated by Django 5.2.1 on 2025-07-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_post_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default=False),
        ),
    ]
