# Generated by Django 5.2.1 on 2025-12-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_content_type_alter_board_object_id'),
        ('posts', '0003_alter_pendinglocationrequest_parent_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='boards', to='posts.post'),
        ),
    ]
