# Generated by Django 5.2.1 on 2025-12-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_posts'),
        ('seekers', '0003_alter_pendingseekerlocationrequest_parent_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='seeker_posts',
            field=models.ManyToManyField(blank=True, related_name='boards', to='seekers.seekerpost'),
        ),
    ]
