# Generated by Django 5.2.1 on 2025-10-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='PostBoard', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='Board for all new approved posts.')),
            ],
        ),
    ]
